app/forms/login.py
from flask.ext.wtf import Form, TextField, PasswordField, Required


class LoginForm(Form):
    email = TextField("Email", validators=[Required()])
    password = PasswordField("Password", validators=[Required()])

app/forms/signup.py
from flask.ext.wtf import Form, TextField, Required, PasswordField, Length,\
                         Email


class SignupForm(Form):
    email = TextField("E-Mail", validators=[Required(), Email()])
    password = PasswordField("Choose Password",
            validators=[Required(), Length(min=4,
        max=50)])

app/controllers/default.py
from flask import Blueprint, render_template, g, session, flash,\
    redirect, url_for, request
from app.models import User, ShairportService, AudioService,\
                        SystemStatusService, DeploySetting,\
                        WifiService, MisterAudioPlayer
from app.forms import LoginForm, SignupForm
from app import application

import subprocess
import sys

controller = Blueprint("default", __name__, url_prefix="")

@controller.route('/player', methods=['GET', 'POST'])
def player():
    player = MisterAudioPlayer()
    return render_template('default/player.html', player=player)


@controller.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    return render_template('default/status.html')
    shairport_service = ShairportService()
    audio_service = AudioService()
    wifi_service = WifiService()

    if request.method == 'POST':
        application.jinja_env.cache.clear()
        namespace = request.form.get('namespace', None)

        if namespace == ShairportService.namespace():
            if shairport_service.update_from_form(request.form):
                flash("ShairportService updated & restarted.")
                session['reboot_required'].add(ShairportService.namespace())
                shairport_service.restart()
            
            return redirect(url_for('.dashboard'))

        else:

            flash("Error saving shairport data.")
            return redirect(url_for('.dashboard'))

    settings = {}
    settings['audio:device'] = DeploySetting.find_or_create_by_namespace_key('audio', 'device', 'usbaudio').value

    return render_template('default/dashboard.html', settings=settings,
                           shairport_service=shairport_service,
                           audio_service=audio_service,
                           system_status_service=system_status_service)

@controller.route('/', methods=['GET', 'POST'])
def status():
    system_status_service = SystemStatusService()
    system_status_service.query_system()
    return render_template('default/status.html',
                           system_status_service=system_status_service)

@controller.route('/airplay', methods=['GET', 'POST'])
def airplay():
    shairport_service = ShairportService()
    if request.method == 'POST':
        application.jinja_env.cache.clear()
        if shairport_service.update_from_form(request.form):
            flash("AirPlay Service updated & restarted.")
            session['reboot_required'].add(ShairportService.namespace())
            shairport_service.restart()
            return redirect(url_for('.airplay'))
    return render_template('default/airplay.html')

@controller.route('/bluetooth', methods=['GET', 'POST'])
def bluetooth():
    return render_template('default/bluetooth.html')


@controller.route('/advanced', methods=['GET', 'POST'])
def advanced():
    return render_template('default/advanced.html')

@controller.route('/reboot', methods=['GET', 'POST'])
def reboot():
    if request.method == 'POST' and request.form.get('reboot', False):
        print "reboot"
        try:
            subprocess.call('sudo reboot', shell=True)
        except subprocess.CalledProcessError as e:
            print "CalledProcessError: %s" % (e)
            flash("CalledProcessError: %s" % (e))
            return redirect(url_for('.reboot'))
        except OSError as e:
            print "OSError: %s" % (e)
            flash("OSError: %s" % (e))
            return redirect(url_for('.reboot'))
        except ValueError as e:
            print "ValueError: %s" % (e)
            flash("ValueError: %s" % (e))
            return redirect(url_for('.reboot'))
        except:
            print "Unexpected error:", sys.exc_info()[0]
            flash("Unexpected error:", sys.exc_info()[0])
            return redirect(url_for('.reboot'))
    return render_template('default/reboot.html', hide_banners=True)


@controller.route('/software_update', methods=['GET', 'POST'])
def software_update():
    sss = SystemStatusService()
    output = sss.software_update()
    flash(output)
    if output != 'Already up-to-date.\n':
        flash('<strong>You must reboot the device for updates to take effect!</strong>')
    return redirect(url_for('default.advanced'))

@controller.route('/restart_audio', methods=['GET', 'POST'])
def restart_audio():
    audio_service = AudioService()
    output = audio_service.restart_audio()
    flash(output)
    return redirect(url_for('default.advanced'))



@controller.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm(csrf_enabled=False)
    next = None
    if g.user:
        return redirect(url_for(".index"))

    if form.validate_on_submit():
        u = User.login(form.email.data, form.password.data)
        if u:
            g.user = u
            session['user_id'] = g.user.id
            flash("Welcome back")
            return redirect(url_for(".index"))
        else:
            next = request.form.get('next', None)
            flash("Invalid e-mail address or password please try again.")

    if not next:
        next = request.args.get('next', None)
    return render_template("default/login.html", form=form)


@controller.route("/signup", methods=['GET', 'POST'])
def signup():
    if g.user:
        return redirect(url_for(".index"))

    form = SignupForm(csrf_enabled=False)
    if form.validate_on_submit():
        u = User.create(passwd=form.password.data,
                        email=form.email.data)
        if u:
            g.user = u
            session['user_id'] = g.user.id
            return redirect(url_for(".index"))
        else:
            flash("An account already exists with that username.")

    return render_template("default/signup.html", form=form)


@controller.route("/logout")
def logout():
    session.pop("user_id", None)
    session.pop("reboot_required", None)
    g.user = None
    return redirect(url_for(".index"))

app/controllers/music.py
from flask import Blueprint, render_template, g, session, flash,\
    redirect, url_for, request
from app import application
from app.models import MisterAudioPlayer
from app.lib import util

controller = Blueprint("music", __name__, url_prefix="/music")


@controller.route("/play/<string:song>", methods=['GET', 'POST'])
def play(song):
    player = MisterAudioPlayer()
    message = "Play song %r" % song
    player.play(song)
        
    return util.render_json(200, {'song': song})

@controller.route("/play/album/<string:album>", methods=['GET', 'POST'])
def play_album(album):
    player = MisterAudioPlayer()
    message = "Play album %r" % album
    player.play_album(album)
    return util.render_json(200, {'album': album})


# @controller.route("/pause", methods=['GET', 'POST'])
# def pause():
#     print "Pause song"
#     return render_template('music/index.html')


@controller.route("/stop", methods=['GET', 'POST'])
def stop():
    message = "Stop all songs"
    player = MisterAudioPlayer()
    player.stop()
    return util.render_json(200, {})

app/templates/default/advanced.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Maintenance
{%- endblock -%}

{%- block pane_title -%}
     Maintenance &amp; Diagnostics
{%- endblock -%}

{%- block content -%}
    <div class="margin-top-10 margin-bottom-10">
        <ul class="list-reset">
            <li>
                <a class="btn btn-list" href="{{ url_for('default.software_update') }}">
                    Software Update
                </a>
            </li>
            <!--
            <li>
                <a class="btn btn-list" href="{{ url_for('default.reboot') }}">
                    MMDS Cloud Music Update
                </a>
            </li>
            -->
            <li>
                <a class="btn btn-list" href="{{ url_for('default.restart_audio') }}">
                    Restart Wireless Audio Services
                </a>
            </li>
            <!--
            <li>
                <a class="btn btn-list" href="{{ url_for('default.reboot') }}">
                    Empty Playlist Queue
                </a>
            </li>
            -->
            <li>
                <a class="btn btn-list btn-stop" href="{{ url_for('default.reboot') }}">
                Restart Device
                </a>
            </li>
        </ul>
    </div>
{%- endblock -%}

app/templates/default/airplay.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Airplay
{%- endblock -%}

{%- block pane_title -%}
    Airplay
{%- endblock -%}

{%- block content -%}
    <form method="POST" action="{{ url_for('default.airplay') }}">
        <fieldset>
            <div class="device-options">
                <label for="speaker_name"><h5><i class="icon-music"></i>AirPlay Speaker Name</h5></label>
                <input type="text"
                        class="span4"
                        name="speaker_name"
                        placeholder="Enter a name..."
                        data-default="AirPlaySpeaker"
                        value="{{ 'speaker_name' | deploy_setting('shairport') }}" />
            </div>
            <div class="form-submit-buttons">
                <button type="submit" class="btn btn-save btn-block">Save</button>
            </div> 
            
        </fieldset>
    </form>
{%- endblock -%}

app/templates/default/bluetooth.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Bluetooth
{%- endblock -%}

{%- block pane_title -%}
    Bluetooth 4.0
{%- endblock -%}

{%- block content -%}
    <form method="POST" action="{{ url_for('default.bluetooth') }}">
        <fieldset>
            <div class="device-options">
                <label for="speaker_name"><h5><i class="icon-music"></i> Bluetooth Device Name</h5></label>
                <input type="text"
                        class="span4"
                        name="speaker_name"
                        placeholder="Enter a name..."
                        data-default="BluetoothSpeaker"
                        value="{{ 'speaker_name' | deploy_setting('bluetooth') }}" />
                <span class="help-block">Look to pair with this device over bluetooth.</span>
            </div>
            <div class="form-submit-buttons">
                <button type="submit" class="btn btn-save btn-block">Save</button>
            </div> 
            
        </fieldset>
    </form>
{%- endblock -%}

app/templates/default/dashboard.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Dashboard
{%- endblock -%}

{%- block content -%}
    <h2>Dashboard</h2>
    <p>
        Welcome to the admin interface for your sexy new RasPi appliance!
    </p>
    {% include('shared/_flash_messages.html') %}
    <ul class="thumbnails services">
        <li class="span12 hr-double">
        </li>
        <li class="span12 header">
            <h4>System Status</h4>
        </li>
        <li class="span12 hr-single">
        </li>
        <li class="span6 level-2">
            <div>
                <h5>SD Card Space</h5>
                <div class="progress progress-info">
                    <div class="bar" style="width: {{ system_status_service.hdd_percent_consumed }};"></div>
                </div>
                <div class="system-output">
                    Used: {{ (system_status_service.hdd_used / 1024) | format_number("{:,.2f}") }} MB
                    ({{ system_status_service.hdd_percent_consumed }})
                    <br />
                    Free: {{ (system_status_service.hdd_free / 1024) | format_number("{:,.2f}") }} MB
                    <br />
                    Total: {{ (system_status_service.hdd_total / 1024 / 1024) | format_number("{:,.3f}") }} GB
                </div>
            </div>            
        </li>
        <li class="span6 level-2">
                <h5>Memory</h5>
                <div class="progress progress-warning">
                    <div class="bar" style="width: {{ (system_status_service.mem_used / system_status_service.mem_total * 100) }}%;"></div>
                </div>
                <div class="system-output">
                    Used: {{ (system_status_service.mem_used / 1024) | format_number("{:,.3f}") }} MB
                    ({{ (system_status_service.mem_used / system_status_service.mem_total * 100) | format_number("{:,.1f}") }}%)
                    <br />
                    Free: {{ (system_status_service.mem_free / 1024) | format_number("{:,.3f}") }} MB
                    <br />
                    Total: {{ (system_status_service.mem_total / 1024) | format_number("{:,.3f}") }} MB
                </div>
        </li>
        <li class="span12 hr-double">
        </li>
        <li class="span4">
            <h4>Shairport AirPlay Audio</h4>
            <hr>
            <form method="POST" action="{{ url_for('default.dashboard') }}">
                <fieldset>
                    
                    <input type="hidden" name="namespace" value="shairport" />

                    <div class="device-options">
                        <label for="speaker_name"><h5><i class="icon-music"></i> Speaker Name</h5></label>
                        <input type="text"
                                name="speaker_name"
                                placeholder="Enter a name..."
                                class="js-has-default"
                                data-default="AirPlaySpeaker"
                                value="{{ 'speaker_name' | deploy_setting('shairport') }}" />
                        <span class="help-block">Advertises this name over wi-fi.</span>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button class="js-set-default btn">Restore Default</button>
                    </div>
                </fieldset>
            </form>
        </li>
        <li class="span4">
            <h4>Audio Output Hardware</h4>
            <hr>
            <form method="POST" action="{{ url_for('default.dashboard') }}">
                <fieldset>
                    
                    <div class="device-options">
                        <input type="hidden" name="namespace" value="audio" />

                        <label for="device"><h5><i class="icon-volume-up"></i> Preferred Audio Device</h5></label>
                        <select name="device"
                                class="js-has-default"
                                multiple="multiple"
                                data-default="usbaudio">
                            <option value="usbaudio"{{ settings['audio:device'] | selected_on('usbaudio') }}>Hi-Fi USB Audio</option>
                            <option value="pulse"{{ settings['audio:device'] | selected_on('pulse') }}>3.5mm Audio Jack (RasPi PWM)</option>
                            <option value="original"{{ settings['audio:device'] | selected_on('original') }}>RasPi Factory Default</option>
                        </select>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Save*</button>
                    </div>
                </fieldset>
            </form>
        </li>

        <li class="span4">
            <h4>Bluetooth</h4>
            <hr>
            <form method="POST" action="{{ url_for('default.dashboard') }}">
                <fieldset>
                    <div class="device-options">
                        <input type="hidden" name="namespace" value="bluetooth" />

                        <label><h5><i class="icon-signal"></i> Antenna</h5></label>
                        <label class="checkbox" for="enabled">
                            <input type="checkbox" name="enabled" value="1" checked="checked" /> <i class="icon-bluetooth"></i> Enabled
                        </label>
                        
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </fieldset>
            </form>
        </li>

        
    </ul>

    <script type="text/javascript">
        $(document).on('ready', function() {
            $('.js-set-default').on('click', function(event) {
                event.preventDefault();
                event.stopPropagation();

                var inputs = $(this).closest('form').find('input.js-has-default');
                $.each(inputs, function (index, e) {
                    $(e).attr('value', $(e).attr('data-default'));
                });
            });
        });
    </script>

{%- endblock -%}

app/templates/default/index.html
{%- extends "layouts/default.html" -%}

{%- block content -%}
    <p>Lorem ipsum</p>
{%- endblock -%}

app/templates/default/login.html
{%- extends "layouts/default.html" -%}
{%- block content -%}
<h2>Log in</h2>
<form method="POST" action="" class="form-vertical focus-form">
    {{ form.hidden_tag() }}
    <fieldset>
        <div class="focus-content-padded text-center margin-top-10">
            {% for field in form if not (field.type == 'HiddenField' or field.type == 'CSRFTokenField')%}
                <div class="control-group {{ 'error' if field.errors else '' }}">
                    <div class="controls">
                        {{ field(placeholder=field.name.capitalize(), class='input-large', id=field.name) }}
                        {% if field.errors %}
                        <span class="help-inline">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                            <span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            {%- if next -%}
                <input type='hidden' name='next' value='{{ next }}' />
            {%- endif -%}
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Log in</i></button>
        </div>
    </fieldset>
</form>
<script type='text/javascript'>
    $(document).on('ready', function() {
        $('#email').focus();
    });
</script>
{%- endblock -%}

app/templates/default/player.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Mister Audio Player
{%- endblock -%}

{%- block pane_title -%}
    Mister Audio Player
{%- endblock -%}

{%- block content -%}
    <div class="playback-controls list-reset hidden">
        <ul>
            <li>
                <a class="js-map-command btn btn-stop btn-list text-center"
                    href="javascript:void(0);"
                    data-control="stop"
                    data-command="{{ url_for('music.stop') }}">STOP PLAYBACK</a>
            </li>
        </ul>
    </div>

    <div class="album-list list-reset margin-top-10">
        <ul>
        {% for a in player.albums %}
            {% set songlist = player.songlist(a.namebase) %}
            <li>
                <a class="js-reveal btn-list btn-list-group"
                    data-target="#album-{{ loop.index0 }}"
                    href="javascript:void(0);">{{ a.namebase }}</a>
                <ul id="album-{{ loop.index0 }}"
                    class="song-list"
                    data-expanded="false">
                    <li>
                        <a class="js-map-command btn-list btn-list-primary"
                            data-command="{{ url_for('music.play_album', album=a.namebase) }}"
                            data-control="play"
                            href="javascript:void(0);">
                            <i class="icon-play icon-white"></i> Play All {{ songlist|length }} Tracks
                            </a>
                    </li>

                {% for s in songlist %}
                    <li>
                        <a class="js-map-command btn-list"
                        data-command="{{ url_for('music.play', song=s.namebase) }}"
                        data-control="play"
                        href="javascript:void(0);">{{ s.namebase }}</a>
                    </li>
                {% endfor %}
                </ul>
            </li>
        {% endfor %}
        </ul>
    </div>

    <script>
        $(document).on('ready', function () {
            $('.js-reveal').on('click', function () {
                var targetId = $(this).attr('data-target');
                var target = $(targetId);
                if (target && target.attr('data-expanded') == 'false') {
                    $('.btn-list-group').removeClass('active');
                    $(this).addClass('active');
                    $('.song-list').slideUp();
                    $('.song-list').attr('data-expanded', 'false');
                    $(target).slideDown(function () {
                        target.attr('data-expanded', 'true');
                    });
                }
            });

            $('.js-map-command').on('click', function () {
                var command = $(this).attr('data-command');
                var control = $(this).attr('data-control');
                var that = this;
                //console.log(command);
                if (command) {
                    $.post(command, {}, function (json, status) {
                        if (json && json.status.code == 200) {
                            $('.js-map-command').removeClass('active');
                            if (control == "play") {
                                $(that).addClass('active')
                            }

                            if ($('.playback-controls').hasClass('hidden')) {
                                $('.playback-controls').slideDown(function() {
                                    $('.playback-controls').removeClass('hidden');
                                });
                            }

                            if (control == "stop") {
                                $('.playback-controls').slideUp(function() {
                                    $('.playback-controls').addClass('hidden');
                                });
                            }
                        }
                    }, 'json');
                }
            });
        });
        
    </script>
{%- endblock -%}

app/templates/default/reboot.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Mister Audio - Reboot Confirmation
{%- endblock -%}

{%- block pane_title -%}
    Reboot Device
{% endblock %}

{%- block content -%}
    <h4>Are you sure you want to reboot?</h4>
    <div class="well">
        The device shouldn't take more than 15 seconds to come back online.
    </div>
    <form class="clearfix" method="POST" action="{{ url_for('default.reboot') }}">
        <fieldset>
            <div class="margin-top-10 margin-bottom-10">
                <ul class="list-reset">
                    <li>
                        <a href="{{ url_for('default.advanced') }}" class="btn btn-list">No, Go Back</a>
                    </li>
                    <li>
                        <button type="submit" class="btn btn-list btn-block btn-stop" name="reboot" value="1">Yes, Reboot Now</button>
                    </li>
                </ul>
            </div>
        </fieldset>
    </form>
    
{%- endblock -%}

app/templates/default/signup.html
{%- from 'macros/form.html' import quick_form -%}
{%- extends "layouts/default.html" -%}
{%- block content -%}
<h2>Sign up</h2>
{{ quick_form(form, method='POST', action=url_for('.signup'), submit="Sign up") }}
<script type='text/javascript'>
    $(document).on('ready', function() {
        $('#email').focus();
    });
</script>
{%- endblock -%}

app/templates/default/status.html
{%- extends "layouts/default.html" -%}

{%- block title -%}
    Mister Audio
{%- endblock -%}

{%- block pane_title -%}
    Device Status
{%- endblock -%}

{%- block content -%}
    <br>
    <div class="row">
        <div class="span6">
            <div class="padding-20">
                <h4>SD Card Space</h4>
                <div class="progress progress-info">
                    <div class="bar" style="width: {{ system_status_service.hdd_percent_consumed }};"></div>
                </div>
                <div class="system-output">
                    Used: {{ (system_status_service.hdd_used / 1024) | format_number("{:,.2f}") }} MB
                    ({{ system_status_service.hdd_percent_consumed }})
                    <br />
                    Free: {{ (system_status_service.hdd_free / 1024) | format_number("{:,.2f}") }} MB
                    <br />
                    Total: {{ (system_status_service.hdd_total / 1024 / 1024) | format_number("{:,.3f}") }} GB
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="padding-20">
            <h4>System Memory</h4>
                <div class="progress progress-warning">
                    <div class="bar" style="width: {{ (system_status_service.mem_used / system_status_service.mem_total * 100) }}%;"></div>
                </div>
                <div class="system-output">
                    Used: {{ (system_status_service.mem_used / 1024) | format_number("{:,.3f}") }} MB
                    ({{ (system_status_service.mem_used / system_status_service.mem_total * 100) | format_number("{:,.1f}") }}%)
                    <br />
                    Free: {{ (system_status_service.mem_free / 1024) | format_number("{:,.3f}") }} MB
                    <br />
                    Total: {{ (system_status_service.mem_total / 1024) | format_number("{:,.3f}") }} MB
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="padding-20 text-center">
            <img src="/static/img/drew-bk-ms.jpg" style="border-radius: 3px" />
        </div>

    </div>
{%- endblock -%}